/* var gulp = require('gulp');
var uglify = require('gulp-uglify');

// Task for minify files generated by Angular
gulp.task('minifyBundles', function () {
   return gulp.src([
  './dist/Angular-Lazy-Loading/main.js', 
  './dist/Angular-Lazy-Loading/polyfills.js',   
  './dist/Angular-Lazy-Loading/runtime.js',
  './dist/Angular-Lazy-Loading/styles.js', 
  './dist/Angular-Lazy-Loading/vendor.js',
  ])
    .pipe(uglify())
    .pipe(gulp.dest('./dist/Angular-Lazy-Loading/'));
}); 
gulp.task('default', gulp.series('minifyBundles'));
 */


var gulp = require('gulp');
var ghPages = require('gulp-gh-pages');

gulp.task('deploy', function () {
  return gulp.src('./dist/Angular-Lazy-Loading/*')
    .pipe(ghPages({ 
      origin: "https://github.com/REIP/demoDeplyment.git",
      remote: "https://REIP:rivera1234@github.com/REIP/project.git",
      force:true,
      push:true
    }))
});

/* var gulp = require('gulp');
var print = require('gulp-print');

gulp.task('message', function() {
  return gulp.src('package.json')
    .pipe(print(function() { return 'HTTP Server Started'; }));
}); */